spring:
  application:
    name: user-ms

  config:
    import: "configserver:"
  cloud:
    config:
      #import-check:
        #enabled: false
      discovery:
        enabled: true
        service-id: configserver

  datasource:
    url: ${USERS_DB_URL:jdbc:postgresql://localhost:5432/users}
    username: ${USERS_DB_USER:postgres}
    password: ${USERS_DB_PASSWORD:postgres}
    hikari:
      schema: app
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none

  liquibase:
    enabled: false
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

server:
  port: 58231
